//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LST {
    
    
    public partial class _Default {
        
        /// <summary>
        /// UCPending1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LST.UserControls.WorkerPendingRequestSummary UCPending1;
        
        /// <summary>
        /// DivWorker control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivWorker;
        
        /// <summary>
        /// UCUserSum control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LST.UserControls.UserLabSummary UCUserSum;
        
        /// <summary>
        /// DivSLSO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivSLSO;
        
        /// <summary>
        /// UCSLSOSum control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LST.UserControls.SLSOLabSummary UCSLSOSum;
        
        /// <summary>
        /// DivSLSOApp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivSLSOApp;
        
        /// <summary>
        /// UCFacReqSum control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LST.UserControls.FacilityApprovalRequestSummary UCFacReqSum;
        
        /// <summary>
        /// UCReqSum control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LST.UserControls.ApprovalRequestSummary UCReqSum;
        
        /// <summary>
        /// DivLSO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivLSO;
        
        /// <summary>
        /// UCFacReqSumLSO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LST.UserControls.FacilityApprovalRequestSummary UCFacReqSumLSO;
        
        /// <summary>
        /// UCReqSumLSO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LST.UserControls.ApprovalRequestSummary UCReqSumLSO;
        
        /// <summary>
        /// DivAdmSVR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivAdmSVR;
        
        /// <summary>
        /// UCReqSumSVR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LST.UserControls.ApprovalRequestSummary UCReqSumSVR;
        
        /// <summary>
        /// DivPM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivPM;
        
        /// <summary>
        /// UCFacReqSumPM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LST.UserControls.FacilityApprovalRequestSummary UCFacReqSumPM;
        
        /// <summary>
        /// DivCoord control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivCoord;
        
        /// <summary>
        /// UCFacReqSumCoord control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LST.UserControls.FacilityApprovalRequestSummary UCFacReqSumCoord;
    }
}
